spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/qingwei
   username: root
   password: root
 redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 5000
mybatis:
  mapperLocations: classpath:mapper/*.xml
logging:
 level:
  root: INFO
  com:
   qingwei:
    springboot: DEBUG
 file: F:\\logs\\springboot.log
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8384/eureka